Revert "Change coverage report generation to call pytest directly"
This reverts commit 5143743b1eb3e96902df84f92caaba0bc07bad98.

diff --git a/.github/workflows/upload_codecov.yml b/.github/workflows/upload_codecov.yml
--- a/.github/workflows/upload_codecov.yml
+++ b/.github/workflows/upload_codecov.yml
@@ -15,15 +15,12 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install coverage codecov pytest pytest-cov pytest-mock pytest-console-scripts
-        pip install .[dev]
+        pip install coverage codecov pytest
+        pip install .
     - name: Generate coverage file
-      env:
-        PACK_NAME: 'hop'
       run: |
-        #coverage run -m pytest || true  # "|| true" ensures that a failed pytest doesn't halt the CI
-        #coverage xml
-        python -m pytest --cov-report term --cov-report xml:coverage.xml --cov $PACK_NAME
+        coverage run -m pytest || true  # "|| true" ensures that a failed pytest doesn't halt the CI
+        coverage xml
     - name: Upload results to Codecov
       uses: codecov/codecov-action@v1
       with:
